// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: Smart_Gadget

#ifndef _UI_COMP_SMALL_LABEL_H
#define _UI_COMP_SMALL_LABEL_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT Small Label
#define UI_COMP_SMALL_LABEL_SMALL_LABEL 0
#define _UI_COMP_SMALL_LABEL_NUM 1
lv_obj_t * ui_Small_Label_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
