// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: Smart_Gadget

#include "../ui.h"

void ui_comp_Alarm_Comp_create_hook(lv_obj_t * comp)
{
}

void ui_comp_Clock_Dot_create_hook(lv_obj_t * comp)
{
}

void ui_comp_Scrolldots_create_hook(lv_obj_t * comp)
{
}

void ui_comp_Small_Label_create_hook(lv_obj_t * comp)
{
}
