// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.4
// Project name: Smartwatch

#include "../ui.h"

void ui_comp_batterygroup_create_hook(lv_obj_t * comp)
{
}
