// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.4
// Project name: Smartwatch

#ifndef _UI_COMP_BATTERYGROUP_H
#define _UI_COMP_BATTERYGROUP_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT batterygroup
#define UI_COMP_BATTERYGROUP_BATTERYGROUP 0
#define UI_COMP_BATTERYGROUP_FLASH 1
#define UI_COMP_BATTERYGROUP_BATTERY_PERCENT 2
#define _UI_COMP_BATTERYGROUP_NUM 3
lv_obj_t * ui_batterygroup_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
