// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: Smart_Gadget

#ifndef _UI_COMP_ALARM_COMP_H
#define _UI_COMP_ALARM_COMP_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT Alarm Comp
#define UI_COMP_ALARM_COMP_ALARM_COMP 0
#define UI_COMP_ALARM_COMP_ALARM_NUM2 1
#define UI_COMP_ALARM_COMP_PERIOD 2
#define UI_COMP_ALARM_COMP_SWITCH1 3
#define _UI_COMP_ALARM_COMP_NUM 4
lv_obj_t * ui_Alarm_Comp_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
