// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.4
// Project name: Smartwatch

#include "../ui.h"

void ui_call_screen_init(void)
{
    ui_call = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_call, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_bg_3 = lv_img_create(ui_call);
    lv_img_set_src(ui_bg_3, &ui_img_bg3_png);
    lv_obj_set_width(ui_bg_3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_bg_3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_bg_3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_bg_3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_bg_3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_avatar = lv_img_create(ui_call);
    lv_img_set_src(ui_avatar, &ui_img_samatha_png);
    lv_obj_set_width(ui_avatar, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_avatar, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_avatar, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_avatar, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_avatar, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_avatar_label = lv_label_create(ui_call);
    lv_obj_set_width(ui_avatar_label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_avatar_label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_avatar_label, 0);
    lv_obj_set_y(ui_avatar_label, 10);
    lv_obj_set_align(ui_avatar_label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_avatar_label, "SAMANTHA");
    lv_obj_set_style_text_color(ui_avatar_label, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_avatar_label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_avatar_label, &ui_font_H1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_call_time = lv_label_create(ui_call);
    lv_obj_set_width(ui_call_time, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_call_time, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_call_time, 0);
    lv_obj_set_y(ui_call_time, 46);
    lv_obj_set_align(ui_call_time, LV_ALIGN_CENTER);
    lv_label_set_text(ui_call_time, "01:25.18");
    lv_obj_set_style_text_color(ui_call_time, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_call_time, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_call_time, &ui_font_Subtitle, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_button_top3 = lv_obj_create(ui_call);
    lv_obj_set_width(ui_button_top3, 70);
    lv_obj_set_height(ui_button_top3, 70);
    lv_obj_set_x(ui_button_top3, -86);
    lv_obj_set_y(ui_button_top3, 106);
    lv_obj_set_align(ui_button_top3, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_button_top3, LV_STATE_CHECKED);       /// States
    lv_obj_clear_flag(ui_button_top3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_button_top3, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_button_top3, lv_color_hex(0xEE1E1E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_button_top3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_button_top3, lv_color_hex(0xEE1E1E), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_button_top3, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_color(ui_button_top3, lv_color_hex(0xEE1E1E), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_button_top3, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_button_top_icon3 = lv_img_create(ui_button_top3);
    lv_img_set_src(ui_button_top_icon3, &ui_img_call2_png);
    lv_obj_set_width(ui_button_top_icon3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_button_top_icon3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_button_top_icon3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_button_top_icon3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_button_top_icon3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_line1 = lv_img_create(ui_button_top3);
    lv_img_set_src(ui_line1, &ui_img_btn_bg_1_png);
    lv_obj_set_width(ui_line1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_line1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_line1, 9);
    lv_obj_set_y(ui_line1, -3);
    lv_obj_set_align(ui_line1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_line1, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_line1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_button_down2 = lv_obj_create(ui_call);
    lv_obj_set_width(ui_button_down2, 70);
    lv_obj_set_height(ui_button_down2, 70);
    lv_obj_set_x(ui_button_down2, 63);
    lv_obj_set_y(ui_button_down2, 110);
    lv_obj_set_align(ui_button_down2, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_button_down2, LV_STATE_CHECKED);       /// States
    lv_obj_clear_flag(ui_button_down2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_button_down2, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_button_down2, lv_color_hex(0x1EEE20), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_button_down2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_button_down2, lv_color_hex(0xEE1E1E), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_button_down2, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_color(ui_button_down2, lv_color_hex(0xEE1E1E), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_button_down2, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_button_down_icon3 = lv_img_create(ui_button_down2);
    lv_img_set_src(ui_button_down_icon3, &ui_img_house_png);
    lv_obj_set_width(ui_button_down_icon3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_button_down_icon3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_button_down_icon3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_button_down_icon3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_button_down_icon3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_button_top3, ui_event_button_top3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_button_down2, ui_event_button_down2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_call, ui_event_call, LV_EVENT_ALL, NULL);

}
