// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.4
// Project name: Smartwatch

#include "../ui.h"

void ui_watch_digital_screen_init(void)
{
    ui_watch_digital = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_watch_digital, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_watch_digital, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_watch_digital, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_bg_1 = lv_img_create(ui_watch_digital);
    lv_img_set_src(ui_bg_1, &ui_img_bg1_png);
    lv_obj_set_width(ui_bg_1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_bg_1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_bg_1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_bg_1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_bg_1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_hour_group = lv_obj_create(ui_watch_digital);
    lv_obj_set_width(ui_hour_group, 289);
    lv_obj_set_height(ui_hour_group, 222);
    lv_obj_clear_flag(ui_hour_group, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_hour_group, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_hour_group, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_label_hour_1 = lv_label_create(ui_hour_group);
    lv_obj_set_width(ui_label_hour_1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_label_hour_1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_label_hour_1, -5);
    lv_obj_set_y(ui_label_hour_1, 45);
    lv_label_set_text(ui_label_hour_1, "0");
    lv_obj_set_style_text_color(ui_label_hour_1, lv_color_hex(0x393939), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_label_hour_1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_label_hour_1, &ui_font_Number_extra, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_label_hour_2 = lv_label_create(ui_hour_group);
    lv_obj_set_width(ui_label_hour_2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_label_hour_2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_label_hour_2, 98);
    lv_obj_set_y(ui_label_hour_2, 45);
    lv_label_set_text(ui_label_hour_2, "3");
    lv_obj_set_style_text_color(ui_label_hour_2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_label_hour_2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_label_hour_2, &ui_font_Number_extra, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_label_min = lv_label_create(ui_watch_digital);
    lv_obj_set_width(ui_label_min, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_label_min, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_label_min, 160);
    lv_obj_set_y(ui_label_min, 184);
    lv_label_set_text(ui_label_min, "27");
    lv_obj_set_style_text_color(ui_label_min, lv_color_hex(0xEE1E1E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_label_min, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_label_min, &ui_font_Number_big, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_battery_group2 = lv_obj_create(ui_watch_digital);
    lv_obj_set_width(ui_battery_group2, 77);
    lv_obj_set_height(ui_battery_group2, 22);
    lv_obj_set_x(ui_battery_group2, -2);
    lv_obj_set_y(ui_battery_group2, 17);
    lv_obj_set_align(ui_battery_group2, LV_ALIGN_TOP_MID);
    lv_obj_set_flex_flow(ui_battery_group2, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_battery_group2, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_battery_group2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_battery_group2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_battery_group2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_battery_group2, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_battery_group2, 8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_flash2 = lv_img_create(ui_battery_group2);
    lv_img_set_src(ui_flash2, &ui_img_flash_png);
    lv_obj_set_width(ui_flash2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_flash2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_flash2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_flash2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_flash2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_battery_percent2 = lv_label_create(ui_battery_group2);
    lv_obj_set_width(ui_battery_percent2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_battery_percent2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_battery_percent2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_battery_percent2, "86%");
    lv_obj_set_style_text_color(ui_battery_percent2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_battery_percent2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_battery_percent2, &ui_font_Title, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_date_group1 = lv_obj_create(ui_watch_digital);
    lv_obj_set_width(ui_date_group1, 100);
    lv_obj_set_height(ui_date_group1, 82);
    lv_obj_set_x(ui_date_group1, 95);
    lv_obj_set_y(ui_date_group1, 62);
    lv_obj_set_align(ui_date_group1, LV_ALIGN_TOP_MID);
    lv_obj_set_flex_flow(ui_date_group1, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_date_group1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_date_group1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_date_group1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_date_group1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_day1 = lv_label_create(ui_date_group1);
    lv_obj_set_width(ui_day1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_day1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_day1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_day1, "MON");
    lv_obj_set_style_text_color(ui_day1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_day1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_day1, &ui_font_Subtitle, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_month1 = lv_label_create(ui_date_group1);
    lv_obj_set_width(ui_month1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_month1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_month1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_month1, "18 FEB");
    lv_obj_set_style_text_color(ui_month1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_month1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_month1, &ui_font_Title, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_year1 = lv_label_create(ui_date_group1);
    lv_obj_set_width(ui_year1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_year1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_year1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_year1, "2022");
    lv_obj_set_style_text_color(ui_year1, lv_color_hex(0x6B6B6B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_year1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_year1, &ui_font_Title, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_weather_group_2 = lv_obj_create(ui_watch_digital);
    lv_obj_set_width(ui_weather_group_2, 106);
    lv_obj_set_height(ui_weather_group_2, 44);
    lv_obj_set_x(ui_weather_group_2, -86);
    lv_obj_set_y(ui_weather_group_2, 45);
    lv_obj_set_align(ui_weather_group_2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_weather_group_2, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_weather_group_2, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_weather_group_2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_weather_group_2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_weather_group_2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_degree_2 = lv_label_create(ui_weather_group_2);
    lv_obj_set_width(ui_degree_2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_degree_2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_degree_2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_degree_2, "25°");
    lv_obj_set_style_text_color(ui_degree_2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_degree_2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_degree_2, &ui_font_H1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_cloud_fog_2 = lv_img_create(ui_weather_group_2);
    lv_img_set_src(ui_cloud_fog_2, &ui_img_weather_sun_cloud_png);
    lv_obj_set_width(ui_cloud_fog_2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_cloud_fog_2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_cloud_fog_2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_cloud_fog_2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_cloud_fog_2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_weather_title_group_3 = lv_obj_create(ui_watch_digital);
    lv_obj_set_width(ui_weather_title_group_3, 200);
    lv_obj_set_height(ui_weather_title_group_3, 50);
    lv_obj_set_x(ui_weather_title_group_3, 2);
    lv_obj_set_y(ui_weather_title_group_3, -42);
    lv_obj_set_align(ui_weather_title_group_3, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_weather_title_group_3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_weather_title_group_3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_weather_title_group_3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_weather_text_3 = lv_label_create(ui_weather_title_group_3);
    lv_obj_set_width(ui_weather_text_3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_weather_text_3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_weather_text_3, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_weather_text_3, "Partly Cloudy");
    lv_obj_set_style_text_color(ui_weather_text_3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_weather_text_3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_weather_text_3, &ui_font_Title, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_weather_degree_3 = lv_label_create(ui_weather_title_group_3);
    lv_obj_set_width(ui_weather_degree_3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_weather_degree_3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_weather_degree_3, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_weather_degree_3, "Max: 18° Min: 12°");
    lv_obj_set_style_text_color(ui_weather_degree_3, lv_color_hex(0x6D6D6D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_weather_degree_3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_weather_degree_3, &ui_font_Title, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_sec_dot = lv_img_create(ui_watch_digital);
    lv_img_set_src(ui_sec_dot, &ui_img_sec_dot_png);
    lv_obj_set_width(ui_sec_dot, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_sec_dot, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_sec_dot, 0);
    lv_obj_set_y(ui_sec_dot, -190);
    lv_obj_set_align(ui_sec_dot, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_sec_dot, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_sec_dot, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_pivot(ui_sec_dot, 4, 194);

    ui_weather_dots_group2 = lv_obj_create(ui_watch_digital);
    lv_obj_set_width(ui_weather_dots_group2, 50);
    lv_obj_set_height(ui_weather_dots_group2, 20);
    lv_obj_set_align(ui_weather_dots_group2, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_flex_flow(ui_weather_dots_group2, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_weather_dots_group2, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_weather_dots_group2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_weather_dots_group2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_weather_dots_group2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_weather_dots_group2, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_weather_dots_group2, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dot14 = lv_obj_create(ui_weather_dots_group2);
    lv_obj_set_width(ui_dot14, 10);
    lv_obj_set_height(ui_dot14, 10);
    lv_obj_set_align(ui_dot14, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_dot14, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_dot14, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dot15 = lv_obj_create(ui_weather_dots_group2);
    lv_obj_set_width(ui_dot15, 6);
    lv_obj_set_height(ui_dot15, 6);
    lv_obj_set_align(ui_dot15, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_dot15, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_dot15, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_dot15, lv_color_hex(0x676767), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_dot15, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_button_top = lv_obj_create(ui_watch_digital);
    lv_obj_set_width(ui_button_top, 70);
    lv_obj_set_height(ui_button_top, 70);
    lv_obj_set_x(ui_button_top, 145);
    lv_obj_set_y(ui_button_top, -175);
    lv_obj_set_align(ui_button_top, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_button_top, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_button_top, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_button_top, lv_color_hex(0xEE1E1E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_button_top, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_button_top, lv_color_hex(0xEE1E1E), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_button_top, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_color(ui_button_top, lv_color_hex(0xEE1E1E), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_button_top, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_button_top_icon1 = lv_img_create(ui_button_top);
    lv_img_set_src(ui_button_top_icon1, &ui_img_call1_png);
    lv_obj_set_width(ui_button_top_icon1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_button_top_icon1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_button_top_icon1, -9);
    lv_obj_set_y(ui_button_top_icon1, 7);
    lv_obj_set_align(ui_button_top_icon1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_button_top_icon1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_button_top_icon1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_button_down = lv_obj_create(ui_watch_digital);
    lv_obj_set_width(ui_button_down, 70);
    lv_obj_set_height(ui_button_down, 70);
    lv_obj_set_x(ui_button_down, 145);
    lv_obj_set_y(ui_button_down, 175);
    lv_obj_set_align(ui_button_down, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_button_down, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_button_down, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_button_down, lv_color_hex(0xEE1E1E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_button_down, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_button_down, lv_color_hex(0xEE1E1E), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_button_down, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_color(ui_button_down, lv_color_hex(0xEE1E1E), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_button_down, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_button_down_icon1 = lv_img_create(ui_button_down);
    lv_img_set_src(ui_button_down_icon1, &ui_img_weather_png);
    lv_obj_set_width(ui_button_down_icon1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_button_down_icon1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_button_down_icon1, -12);
    lv_obj_set_y(ui_button_down_icon1, -9);
    lv_obj_set_align(ui_button_down_icon1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_button_down_icon1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_button_down_icon1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_button_top, ui_event_button_top, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_button_down, ui_event_button_down, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_watch_digital, ui_event_watch_digital, LV_EVENT_ALL, NULL);

}
